#ifndef RMYSQLDAO_GLOBAL_H
#define RMYSQLDAO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RMYSQLDAO_LIBRARY)
#  define RMYSQLDAOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RMYSQLDAOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RMYSQLDAO_GLOBAL_H
